Iter5
AnthonyNikitin/go-musthave-shortener-tpl pull request #5
Opened 2023-12-16 17:24 UTC by AnthonyNikitin

added environment configuration with priority to env

2023-12-18 14:12 UTC, tmvrus requested changes

2023-12-18 14:12 UTC, tmvrus commented on internal/app/hasher/hasher.go
> +	}
если Encode вернет ошибку, os.Exit завершит приложение, это довольно странно из-за одной ошибки, останавливать работу сервиса целиком

2023-12-18 14:12 UTC, tmvrus commented on internal/app/config/config.go
> +func (configuration *Configuration) ParseConfiguration() {
в Go принято давать короткие имена для "method receivers"
`(c *Configuration)`

2023-12-18 14:12 UTC, tmvrus commented on internal/app/config/config.go
> +	flag.Func("b", "base url address of the response", func(s string) error {
flag.Func может вернуть ошибку, а ее никто не обрабатывает

2023-12-18 14:12 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusBadRequest)
return не хватает

2023-12-18 14:12 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	}
мы никогда не узнаем какая была ошибка и почему она случилась, что бы этого не случилось - ошибку нужно логировать

2023-12-20 18:13 UTC, AnthonyNikitin commented on internal/app/hasher/hasher.go
> +	}
done; теперь возвращаем ошибку

2023-12-20 18:13 UTC, AnthonyNikitin commented on internal/app/config/config.go
> +func (configuration *Configuration) ParseConfiguration() {
done

2023-12-20 18:14 UTC, AnthonyNikitin commented on internal/app/config/config.go
> +	flag.Func("b", "base url address of the response", func(s string) error {
Т.к. тут идет проверка флагов, то пользователю вернётся ошибка в stdout с help сообщением как пользоваться флагами. Я бы тут оставил как есть :)

2023-12-20 18:14 UTC, AnthonyNikitin commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusBadRequest)
done; добавил return и логгирование ошибки

2023-12-20 18:14 UTC, AnthonyNikitin commented on internal/app/handlers/handlers.go
> +	}
done; добавил логгирование ошибки

2023-12-21 12:03 UTC, tmvrus commented on internal/app/config/config.go
> +	flag.Func("b", "base url address of the response", func(s string) error {
разумно

2023-12-21 12:04 UTC, tmvrus approved these changes

2023-12-21 17:00 UTC, merged