Iter9
AnthonyNikitin/go-musthave-shortener-tpl pull request #9
Opened 2023-12-30 12:30 UTC by AnthonyNikitin

added ability to store short urls in file

2024-01-05 11:10 UTC, tmvrus requested changes
нужно навести порядок с использованием fmt.Println

2024-01-08 10:15 UTC, AnthonyNikitin commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusBadRequest)
done

2024-01-08 10:15 UTC, AnthonyNikitin commented on internal/app/writers/response_writer.go
> +type LoggingResponseWriter struct {
Это райтер который используется для логгирования респонса через мидлвару

2024-01-09 19:08 UTC, tmvrus approved these changes

2024-01-11 02:29 UTC, merged